### ISSUE TITLE
"typ" (Type) Header Parameter

### ISSUE THREAD

**Issue by idonothaveacat** [nowakowskir/php-jwt#1]
The HEADER parameter type of 'JWT' is optional (see: https://tools.ietf.org/html/rfc7519#page-11)

When using tokens that don't have this header set, this library throws an exception that an "UnsupportedTokenTypeException" is being used.

Could you please update the validation to accommodate this optional header so it does not throw an exception when not set?

**Comment by nowakowskir** [comment]
Your suggestion has been addressed https://github.com/nowakowskir/php-jwt/tree/2.1.1
