### ISSUE TITLE
Works with HS256 but not RS256,RS384,RS512

### ISSUE THREAD

**Issue by jshster** [nowakowskir/php-jwt#5]
Got an issue and haven't been able to find the solution.  I've followed your instructions and have attempted to sign a JWT.  It works with HS256 but as soon as I switch the algorithm to RS256,RS384 or RS512 I receive the following error and I can't for the life of me work out what I'm doing wrong.  I know it relates to the private/public keys but not sure exactly what.

Warning: openssl_sign(): supplied key param cannot be coerced into a private key

I've tried using openssl_pkey_get_private and openssl_get_private key but it never seems to return anything (and yes I have passed the passphrase in the call).

Any ideas would be appreciated
Cheers

**Comment by nowakowskir** [comment]
You need to provide valid private/public key pair. For HS256 it accepts any string as the key is symmetric, but for RS-algorithms it's not the case.

`ssh-keygen -t rsa -b 4096 -m PEM -E SHA256 -f private.key`
`openssl rsa -in private.key -pubout -outform PEM -out public.pub`

Then use content of `private.key` to sign the token, and content from `public.pub` to verify the token.
